import type { BoardConfig } from "@/types/content";

/** 초기 시드(seed) 게시판 설정 — Firestore에 boards 컬렉션이 비어있을 때 사용 */
export const DEFAULT_BOARDS: BoardConfig[] = [
  // ── 콘텐츠(공개 허브) ──
  {
    key: "media-lecture",
    label: "강의 영상",
    group: "media",
    layout: "grid",
    writeRole: "admin",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Video",
    order: 1,
    isActive: true,
  },
  {
    key: "media-workathon",
    label: "워크톤 현장",
    group: "media",
    layout: "grid",
    writeRole: "admin",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Clapperboard",
    order: 2,
    isActive: true,
  },
  {
    key: "media-interview",
    label: "강사 인터뷰",
    group: "media",
    layout: "grid",
    writeRole: "admin",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Mic",
    order: 3,
    isActive: true,
  },
  {
    key: "media-promo",
    label: "홍보 영상",
    group: "media",
    layout: "grid",
    writeRole: "admin",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Megaphone",
    order: 4,
    isActive: true,
  },
  {
    key: "media-gallery",
    label: "갤러리",
    group: "media",
    layout: "grid",
    writeRole: "member",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Image",
    order: 5,
    isActive: true,
  },
  {
    key: "media-resource",
    label: "자료실",
    group: "media",
    layout: "list",
    writeRole: "member",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "FileText",
    order: 6,
    isActive: true,
  },

  // ── 커뮤니티 ──
  {
    key: "community-notice",
    label: "공지사항",
    group: "community",
    layout: "list",
    writeRole: "admin",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "Bell",
    order: 10,
    isActive: true,
  },
  {
    key: "community-free",
    label: "묻고 답하기",
    group: "community",
    layout: "list",
    writeRole: "member",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "MessageSquare",
    order: 11,
    isActive: true,
  },
  {
    key: "community-qna",
    label: "Q&A",
    group: "community",
    layout: "list",
    writeRole: "member",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: true,
    requireApproval: false,
    icon: "HelpCircle",
    order: 12,
    isActive: true,
  },
  {
    key: "community-review",
    label: "수강후기",
    group: "community",
    layout: "list",
    writeRole: "member",
    allowComments: true,
    allowLikes: true,
    allowBookmarks: false,
    requireApproval: true,
    icon: "Star",
    order: 13,
    isActive: true,
  },
  {
    key: "community-faq",
    label: "FAQ",
    group: "community",
    layout: "faq",
    writeRole: "admin",
    allowComments: false,
    allowLikes: false,
    allowBookmarks: false,
    requireApproval: false,
    icon: "CircleHelp",
    order: 14,
    isActive: true,
  },
];

/** boardKey → BoardConfig 빠른 조회 맵 */
export const BOARD_MAP = new Map(DEFAULT_BOARDS.map((b) => [b.key, b]));

/** 그룹별 게시판 필터링 */
export function getBoardsByGroupDefault(
  group: BoardConfig["group"],
): BoardConfig[] {
  return DEFAULT_BOARDS.filter((b) => b.group === group && b.isActive);
}
